### ISSUE TITLE
Add Codeship

### ISSUE THREAD

**Issue by StephanBijzitter** [siddharthkp/ci-env#11]
For reference: https://documentation.codeship.com/pro/builds-and-configuration/environment-variables/#default-environment-variables

I'll start on the implementation in a fork, but it may take some time as I'll be doing this in my spare time. Though, quickly looking through the code, it shouldn't be difficult :-)

**Comment by siddharthkp** [comment]
Go for it!

**Comment by StephanBijzitter** [comment]
Well, turned out to be quite a quickie.
