### ISSUE TITLE
Add `base_branch` to exported envs

### ISSUE THREAD

**Issue by iamogbz** [siddharthkp/ci-env#34]
Currently it does not look like there's a way to get the base branch being targeted in the case of a pull request.

**Comment by siddharthkp** [comment]
Which CI platform are you on? 

Does this bit help?: https://github.com/siddharthkp/ci-env/blob/master/index.js#L19-L22

**Comment by iamogbz** [comment]
@siddharthkp want to use it for a tool that could be run on any env. Looks like
https://github.com/siddharthkp/ci-env/blob/cc891b5f657f39688d72e74e2c6308ffa4224b96/index.js#L19-L22
only tell you current branch.
When running from a pull request e.g.
<img width="202" alt="Screen Shot 2020-04-27 at 2 09 55 PM" src="https://user-images.githubusercontent.com/2528959/80405558-c6c9bf00-8890-11ea-9a3f-b13534966814.png">
It would tell you `develop`, but I want to also know which branch is being targeted i.e. `master`

**Comment by siddharthkp** [comment]
ah, I understand now. Does travis/other CI expose that information?

**Comment by iamogbz** [comment]
@siddharthkp travis has `TRAVIS_BRANCH` https://docs.travis-ci.com/user/environment-variables/, I think github has `GITHUB_BASE_REF`. Not certain about others, but hopefully they would

**Comment by siddharthkp** [comment]
Perfect, would you like to shot on the implementation?
