### ISSUE TITLE
Allow custom CI implementations

### ISSUE THREAD

**Issue by siddharthkp** [siddharthkp/ci-env#5]
`ci-env` supports travis, circle, wercker and [drone](https://github.com/siddharthkp/ci-env/pull/3) right now.

But, there are self hosted or containerised environments where these will not be used.

We can add support for those by supporting generic environment variables.

```js
else if (process.env.CI === 'custom') {
   repo = process.env.CI_REPO,
   branch = process.env.CI_BRANCH
   ...
}
```

**Comment by StephanBijzitter** [comment]
What about a `ci-env.js` file in the root of the consuming project (next to `package.json`) that can be picked up if present? This file would export the variables with values. This would allow anyone to create any kind of custom environment.

**Comment by siddharthkp** [comment]
I would prefer picking them from the environment because that's how all of the CI tools expose their variables.

Even though picking from `ci-env.js` would work, it's a new convention set up by us that folks will have to follow 😄

**Comment by StephanBijzitter** [comment]
True, but it would give people who want to use your package (or bundlesize) with an unsupported CI an immediate means to get started. As a nice bonus for you, the config file could quite easily be turned into a pull request here. It should definitely not be required, but it's a good addition I think.

**Comment by siddharthkp** [comment]
If you're keen on using a file, creating a .env + reading it with https://npmjs.com/dotenv would be closer to the environment variable way.

**Comment by StephanBijzitter** [comment]
That's actually even better.

**Comment by siddharthkp** [comment]
We have support for this now! 

https://github.com/siddharthkp/ci-env/blob/master/index.js#L84-L94
